
language: python
python:
  - "3.8"
before_install:
  - pip install pyqt5
  - pip install google-api-python-client
  - pip install google_auth_oauthlib
script:
  - python Khaled_Unit_test.py
  - python Omar_Unit_Test.py
  

